### PR TITLE
Add fastspell conservative and agressive to the comparison

### LINKED ISSUE #188: Add fastspell to the comparison
[fastspell](https://github.com/mbanon/fastspell) uses a combination of fastText and dictionaries to identify the language. It would be interesting to see how it compares to lingua-py.

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #188

### CODE REVIEW

**Comment by marco-c** [comment]
The PR is marked as draft because Poetry is failing to install the package.

**Comment by marco-c** [comment]
I managed to find a way to fix the installation error. With Python 3.10, which I'm using, we need to install at least cyhunspell 2.0.3 (which isn't published on PyPI yet).

**Comment by pemistahl** [comment]
Thank you Marco. I will deal with your PR shortly. MyPy is reporting type checking failures. Can you fix them please?

**Comment by pemistahl** [comment]
You always need to run the Black code formatter as well, please. Otherwise, the build fails.

**Comment by marco-c** [comment]
Yeah, I'm too used to my projects where mypy, black and other linting are run on a commit hook :)

**Pull request merged**
